[sprite_sheet.background]
texture_image = "assets/textures/background.png"
sprites = [
    { x = 0, y = 0, width = 720, height = 600 },
]

[sprite_sheet.game]
texture_image = "assets/textures/game.png"
sprites = [
    { x = 0,   y = 96, width = 144, height = 24 },
    { x = 144, y = 96, width = 24,  height = 24 },
]
