[[entity]]

    [entity.components.Text]
    id = "life"
    text = "LIFES: 5"
    font_face = { font = "joystix", options = { size = 30.0, hinting = "Full" } }
    color = [255, 255, 255, 255]

    [entity.components.UITransform]
    translation = { x = 710, y = 590 }
    pivot = "TopRight"
