[[entity]]

[entity.components.Text]
id = "life"
text = "LIVES: 5"
font_face = { font = "joystix", options.size = 25.0 }
color = [255, 255, 255, 255]

[entity.components.UITransform]
translation = { x = -10, y = -10 }
origin = "TopRight"
pivot = "TopRight"
