# Paddle
[[entity]]

    [entity.components.SpriteRender]
    sprite_sheet_name = "game"
    sprite_number = 18

    [entity.components.Transform]
    translation = { x = 360.0, y = 12.0 }

    [entity.components.Paddle]
    width = 144.0
    height = 24.0


# Ball
[[entity]]

    [entity.components.SpriteRender]
    sprite_sheet_name = "game"
    sprite_number = 19

    [entity.components.Transform]
    translation = { x = 360.0, y = 35.0 }
    depth = 0.2

    [entity.components.Ball]
    radius = 11.0
    velocity = 450.0
    direction = { x = 0.0, y = 1.0 }

    [entity.components.StickyBall]
    width_extent = 52.0
    period = 2.0


# Blocks
[[entity]]
components = { SpriteRender = { sprite_sheet_name = "game", sprite_number = 0 }, Transform = { translation = { x = 104.0, y = 350.0 } }, Block = {} }
[[entity]]
components = { SpriteRender = { sprite_sheet_name = "game", sprite_number = 0 }, Transform = { translation = { x = 168.0, y = 350.0 } }, Block = {} }
[[entity]]
components = { SpriteRender = { sprite_sheet_name = "game", sprite_number = 0 }, Transform = { translation = { x = 232.0, y = 350.0 } }, Block = {} }
[[entity]]
components = { SpriteRender = { sprite_sheet_name = "game", sprite_number = 0 }, Transform = { translation = { x = 296.0, y = 350.0 } }, Block = {} }
[[entity]]
components = { SpriteRender = { sprite_sheet_name = "game", sprite_number = 0 }, Transform = { translation = { x = 360.0, y = 350.0 } }, Block = {} }
[[entity]]
components = { SpriteRender = { sprite_sheet_name = "game", sprite_number = 0 }, Transform = { translation = { x = 424.0, y = 350.0 } }, Block = {} }
[[entity]]
components = { SpriteRender = { sprite_sheet_name = "game", sprite_number = 0 }, Transform = { translation = { x = 488.0, y = 350.0 } }, Block = {} }
[[entity]]
components = { SpriteRender = { sprite_sheet_name = "game", sprite_number = 0 }, Transform = { translation = { x = 552.0, y = 350.0 } }, Block = {} }
[[entity]]
components = { SpriteRender = { sprite_sheet_name = "game", sprite_number = 0 }, Transform = { translation = { x = 616.0, y = 350.0 } }, Block = {} }

[[entity]]
components = { SpriteRender = { sprite_sheet_name = "game", sprite_number = 1 }, Transform = { translation = { x = 104.0, y = 382.0 } }, Block = {} }
[[entity]]
components = { SpriteRender = { sprite_sheet_name = "game", sprite_number = 1 }, Transform = { translation = { x = 168.0, y = 382.0 } }, Block = {} }
[[entity]]
components = { SpriteRender = { sprite_sheet_name = "game", sprite_number = 1 }, Transform = { translation = { x = 232.0, y = 382.0 } }, Block = {} }
[[entity]]
components = { SpriteRender = { sprite_sheet_name = "game", sprite_number = 1 }, Transform = { translation = { x = 296.0, y = 382.0 } }, Block = {} }
[[entity]]
components = { SpriteRender = { sprite_sheet_name = "game", sprite_number = 1 }, Transform = { translation = { x = 360.0, y = 382.0 } }, Block = {} }
[[entity]]
components = { SpriteRender = { sprite_sheet_name = "game", sprite_number = 1 }, Transform = { translation = { x = 424.0, y = 382.0 } }, Block = {} }
[[entity]]
components = { SpriteRender = { sprite_sheet_name = "game", sprite_number = 1 }, Transform = { translation = { x = 488.0, y = 382.0 } }, Block = {} }
[[entity]]
components = { SpriteRender = { sprite_sheet_name = "game", sprite_number = 1 }, Transform = { translation = { x = 552.0, y = 382.0 } }, Block = {} }
[[entity]]
components = { SpriteRender = { sprite_sheet_name = "game", sprite_number = 1 }, Transform = { translation = { x = 616.0, y = 382.0 } }, Block = {} }

[[entity]]
components = { SpriteRender = { sprite_sheet_name = "game", sprite_number = 2 }, Transform = { translation = { x = 104.0, y = 414.0 } }, Block = {} }
[[entity]]
components = { SpriteRender = { sprite_sheet_name = "game", sprite_number = 2 }, Transform = { translation = { x = 168.0, y = 414.0 } }, Block = {} }
[[entity]]
components = { SpriteRender = { sprite_sheet_name = "game", sprite_number = 2 }, Transform = { translation = { x = 232.0, y = 414.0 } }, Block = {} }
[[entity]]
components = { SpriteRender = { sprite_sheet_name = "game", sprite_number = 2 }, Transform = { translation = { x = 296.0, y = 414.0 } }, Block = {} }
[[entity]]
components = { SpriteRender = { sprite_sheet_name = "game", sprite_number = 2 }, Transform = { translation = { x = 360.0, y = 414.0 } }, Block = {} }
[[entity]]
components = { SpriteRender = { sprite_sheet_name = "game", sprite_number = 2 }, Transform = { translation = { x = 424.0, y = 414.0 } }, Block = {} }
[[entity]]
components = { SpriteRender = { sprite_sheet_name = "game", sprite_number = 2 }, Transform = { translation = { x = 488.0, y = 414.0 } }, Block = {} }
[[entity]]
components = { SpriteRender = { sprite_sheet_name = "game", sprite_number = 2 }, Transform = { translation = { x = 552.0, y = 414.0 } }, Block = {} }
[[entity]]
components = { SpriteRender = { sprite_sheet_name = "game", sprite_number = 2 }, Transform = { translation = { x = 616.0, y = 414.0 } }, Block = {} }

[[entity]]
components = { SpriteRender = { sprite_sheet_name = "game", sprite_number = 3 }, Transform = { translation = { x = 104.0, y = 446.0 } }, Block = {} }
[[entity]]
components = { SpriteRender = { sprite_sheet_name = "game", sprite_number = 3 }, Transform = { translation = { x = 168.0, y = 446.0 } }, Block = {} }
[[entity]]
components = { SpriteRender = { sprite_sheet_name = "game", sprite_number = 3 }, Transform = { translation = { x = 232.0, y = 446.0 } }, Block = {} }
[[entity]]
components = { SpriteRender = { sprite_sheet_name = "game", sprite_number = 3 }, Transform = { translation = { x = 296.0, y = 446.0 } }, Block = {} }
[[entity]]
components = { SpriteRender = { sprite_sheet_name = "game", sprite_number = 3 }, Transform = { translation = { x = 360.0, y = 446.0 } }, Block = {} }
[[entity]]
components = { SpriteRender = { sprite_sheet_name = "game", sprite_number = 3 }, Transform = { translation = { x = 424.0, y = 446.0 } }, Block = {} }
[[entity]]
components = { SpriteRender = { sprite_sheet_name = "game", sprite_number = 3 }, Transform = { translation = { x = 488.0, y = 446.0 } }, Block = {} }
[[entity]]
components = { SpriteRender = { sprite_sheet_name = "game", sprite_number = 3 }, Transform = { translation = { x = 552.0, y = 446.0 } }, Block = {} }
[[entity]]
components = { SpriteRender = { sprite_sheet_name = "game", sprite_number = 3 }, Transform = { translation = { x = 616.0, y = 446.0 } }, Block = {} }

[[entity]]
components = { SpriteRender = { sprite_sheet_name = "game", sprite_number = 4 }, Transform = { translation = { x = 104.0, y = 478.0 } }, Block = {} }
[[entity]]
components = { SpriteRender = { sprite_sheet_name = "game", sprite_number = 4 }, Transform = { translation = { x = 168.0, y = 478.0 } }, Block = {} }
[[entity]]
components = { SpriteRender = { sprite_sheet_name = "game", sprite_number = 4 }, Transform = { translation = { x = 232.0, y = 478.0 } }, Block = {} }
[[entity]]
components = { SpriteRender = { sprite_sheet_name = "game", sprite_number = 4 }, Transform = { translation = { x = 296.0, y = 478.0 } }, Block = {} }
[[entity]]
components = { SpriteRender = { sprite_sheet_name = "game", sprite_number = 4 }, Transform = { translation = { x = 360.0, y = 478.0 } }, Block = {} }
[[entity]]
components = { SpriteRender = { sprite_sheet_name = "game", sprite_number = 4 }, Transform = { translation = { x = 424.0, y = 478.0 } }, Block = {} }
[[entity]]
components = { SpriteRender = { sprite_sheet_name = "game", sprite_number = 4 }, Transform = { translation = { x = 488.0, y = 478.0 } }, Block = {} }
[[entity]]
components = { SpriteRender = { sprite_sheet_name = "game", sprite_number = 4 }, Transform = { translation = { x = 552.0, y = 478.0 } }, Block = {} }
[[entity]]
components = { SpriteRender = { sprite_sheet_name = "game", sprite_number = 4 }, Transform = { translation = { x = 616.0, y = 478.0 } }, Block = {} }

[[entity]]
components = { SpriteRender = { sprite_sheet_name = "game", sprite_number = 5 }, Transform = { translation = { x = 104.0, y = 510.0 } }, Block = {} }
[[entity]]
components = { SpriteRender = { sprite_sheet_name = "game", sprite_number = 5 }, Transform = { translation = { x = 168.0, y = 510.0 } }, Block = {} }
[[entity]]
components = { SpriteRender = { sprite_sheet_name = "game", sprite_number = 5 }, Transform = { translation = { x = 232.0, y = 510.0 } }, Block = {} }
[[entity]]
components = { SpriteRender = { sprite_sheet_name = "game", sprite_number = 5 }, Transform = { translation = { x = 296.0, y = 510.0 } }, Block = {} }
[[entity]]
components = { SpriteRender = { sprite_sheet_name = "game", sprite_number = 5 }, Transform = { translation = { x = 360.0, y = 510.0 } }, Block = {} }
[[entity]]
components = { SpriteRender = { sprite_sheet_name = "game", sprite_number = 5 }, Transform = { translation = { x = 424.0, y = 510.0 } }, Block = {} }
[[entity]]
components = { SpriteRender = { sprite_sheet_name = "game", sprite_number = 5 }, Transform = { translation = { x = 488.0, y = 510.0 } }, Block = {} }
[[entity]]
components = { SpriteRender = { sprite_sheet_name = "game", sprite_number = 5 }, Transform = { translation = { x = 552.0, y = 510.0 } }, Block = {} }
[[entity]]
components = { SpriteRender = { sprite_sheet_name = "game", sprite_number = 5 }, Transform = { translation = { x = 616.0, y = 510.0 } }, Block = {} }
